### ISSUE TITLE
How to have a footer at the bottom?

### ISSUE THREAD

**Issue by arielt** [ar363/eleventy-stylus-blog-theme#1]
Nice theme!

If the page is not full though, the footer will not be at the bottom, for example, https://ar363.github.io/eleventy-stylus-blog-theme/tags/

Any idea how to change it?

Thanks
Ariel

**Comment by ar363** [comment]
I implemented a fix with css grid. 
Should be at the bottom now...

**Comment by arielt** [comment]
Awesome!
